name: Build Wheels

on:
  push:
    branches:
      - 0.8.x
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "cibuildwheel>=2.0,<3.0"
          python -m pip install "pytest>=8.3.2,<9.0.0"

      - name: Build Wheels
        run: cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: cp312-* cp313-*
          CIBW_TEST_COMMAND: pytest -m "not tracewin and not implementation" {project}/tests
